# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_eventdft_c', [dirname(__file__)])
        except ImportError:
            import _eventdft_c
            return _eventdft_c
        if fp is not None:
            try:
                _mod = imp.load_module('_eventdft_c', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _eventdft_c = swig_import_helper()
    del swig_import_helper
else:
    import _eventdft_c
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class fcomplex(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, fcomplex, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, fcomplex, name)
    __repr__ = _swig_repr
    __swig_setmethods__["r"] = _eventdft_c.fcomplex_r_set
    __swig_getmethods__["r"] = _eventdft_c.fcomplex_r_get
    if _newclass:r = _swig_property(_eventdft_c.fcomplex_r_get, _eventdft_c.fcomplex_r_set)
    __swig_setmethods__["i"] = _eventdft_c.fcomplex_i_set
    __swig_getmethods__["i"] = _eventdft_c.fcomplex_i_get
    if _newclass:i = _swig_property(_eventdft_c.fcomplex_i_get, _eventdft_c.fcomplex_i_set)
    def __init__(self): 
        this = _eventdft_c.new_fcomplex()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _eventdft_c.delete_fcomplex
    __del__ = lambda self : None;
fcomplex_swigregister = _eventdft_c.fcomplex_swigregister
fcomplex_swigregister(fcomplex)


def eventdft(*args):
  return _eventdft_c.eventdft(*args)
eventdft = _eventdft_c.eventdft

def prep_eventdft(*args):
  return _eventdft_c.prep_eventdft(*args)
prep_eventdft = _eventdft_c.prep_eventdft

def free_eventdft():
  return _eventdft_c.free_eventdft()
free_eventdft = _eventdft_c.free_eventdft
# This file is compatible with both classic and new-style classes.


